"""Record a deterministic, model-free tour of the current planner in real OMP.

Run from any directory: python3 scripts/demo/scenario_full.py /tmp/planner.cast
The temporary workspace is generated by fixture.ts and removed on exit. The
recording previews a request but never submits it or calls a model.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import time
from pathlib import Path

from ptydriver import Drivers

REPO = Path(__file__).resolve().parents[2]
ESC, ENTER, DOWN = b"\x1b", b"\r", b"\x1b[B"


def record(cast: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="omp-planner-demo-") as workspace:
        subprocess.run(["bun", str(REPO / "scripts/demo/fixture.ts"), workspace], check=True, capture_output=True)
        print(f"Recording planner tour in {workspace}", flush=True)
        driver = Drivers(
            str(cast),
            argv=["omp", "--no-extensions", "-e", str(REPO / "src/index.ts"), "--no-session", "--no-lsp", "--no-title"],
            cwd=workspace,
            cols=120,
            rows=34,
        )

        def show(seconds: float = 1.0) -> None:
            driver.wait(seconds)

        def expect(text: str, timeout: float = 10.0) -> None:
            observed = "".join(data for _, data in driver.frames)
            deadline = time.monotonic() + timeout
            while time.monotonic() < deadline:
                observed += driver.record_for(0.25)
                if text in observed:
                    return
            raise RuntimeError(f"the OMP demo never showed {text!r}")

        try:
            show(2)
            driver.keys([ESC])  # dismiss the update banner, if shown
            show(0.3)
            driver.frames.clear()  # no startup chatter in the published cast
            driver.started = time.time()

            driver.send(b"/diagram open architecture.json\r")
            show(0.5)
            expect("Block workflow")
            show(1.7)  # nested outline + focused page

            driver.keys([ENTER, DOWN, DOWN, DOWN, ENTER], gap=0.18)
            expect("source: src/flow.ts")
            show(0.8)
            driver.keys([DOWN, DOWN, b"\x1b[6~"], gap=0.2)
            show(0.8)
            driver.keys([b"G"])
            last_line = len((Path(workspace) / "src/flow.ts").read_text().split("\n"))
            expect(f"{last_line}/{last_line}")
            show(1.0)  # the end of the actual file, beyond the cited range
            driver.keys([ESC])
            show(0.6)
            driver.keys([ESC])  # back to the nested outline
            driver.keys([b"j", b"j"], gap=0.25)
            show(1.0)

            driver.keys([b"a"])
            expect("Prune unnecessary blocks")
            # The menu grew with reuse entries; walk to the prune row by its marker
            # instead of counting, so adding an action again does not break the tour.
            for _ in range(12):
                if "› Prune unnecessary blocks" in "".join(data for _, data in driver.frames):
                    break
                driver.keys([DOWN], gap=0.12)
            driver.keys([ENTER], gap=0.12)
            expect("Prune this map")
            show(1.5)  # composed, scoped prompt; do not submit
            driver.keys([ESC])
            show(0.4)
            driver.keys([b"h", b"v"], gap=0.25)
            show(1.8)  # optional coordinate map, same document
        finally:
            driver.finish()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: python3 scripts/demo/scenario_full.py /path/to/demo.cast")
    record(Path(sys.argv[1]).resolve())
